### PR TITLE
fix(k8s/runner): use dynamic client for watches

### LINKED ISSUE #51: Decoding error when watch events arrive
When a `Broker` is created via the [demo chart](https://github.com/deis/steward-demo-s3/tree/new-arch/charts/broker) and steward-cf picks it up, the loop errors with the following error:

```
E1116 22:32:32.254614       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Broker" is registered for version "steward.deis.io/v1"
22:32:32 ERROR k8s.broker loop.go:38 the watch channel was closed
22:32:32 CRITC framework.runner runner.go:60 watch closed
22:32:32 CRITC  main.go:35 error running steward-framework: watch closed
```

I believe the "unable to decode watch event" error is the root cause here. Same issue for `Instance` and `Binding` events.

### PR DESCRIPTION
**Pull request by arschles**
Fixes #51

### CODE REVIEW

**Comment by arschles** [comment]
Currently, I see the following error on startup:

``` console
17:53:26 ERROR framework.k8s loops.go:90 binding loop (the server could not find the requested resource (get bindings.steward.deis.io))
17:53:26 CRITC framework.runner runner.go:63 the server could not find the requested resource (get bindings.steward.deis.io)
17:53:26 CRITC  main.go:35 error running steward-framework: the server could not find the requested resource (get bindings.steward.deis.io)
```

**Comment by arschles** [comment]
progress as of 4e6794107c2c0d0f1622535c15d6b11e0a2bc3dc: steward-cf starts up, but the returned object doesn't appear to be a binding. The loop also does not terminate anymore. Error trace:

``` console
^CENG000656:s3-service-provider aaronschlesinger$ ks logs -f invinvible-jag-steward-3292932084-6yeye
18:18:32 INFO   main.go:14 steward-cf version devel starting
18:18:32 INFO  framework.web.api router.go:23 starting API server on port 8080
18:19:11 DEBUG framework.k8s.binding loop.go:51 binding loop received event
18:19:11 ERROR framework.k8s.binding loop.go:65 add binding event handler failed (not a binding)
```

**Comment by arschles** [comment]
progress as of 0bc4c38a209fe144f566ea75b1b650ba2213c083: `Binding` resource is properly decoded from event, but now can't be updated to `Pending` (probably because we're trying to use a `RESTClient` to do so instead of the dynamic client). Error trace:

``` console
^CENG000656:s3-service-provider aaronschlesinger$ ks logs -f impressive-fly-steward-521021679-t24em
18:35:47 INFO   main.go:14 steward-cf version devel starting
18:35:48 INFO  framework.web.api router.go:23 starting API server on port 8080
18:35:48 DEBUG framework.k8s.binding loop.go:51 binding loop received event
18:35:48 ERROR framework.k8s.binding loop.go:90 error updating binding state to Pending
18:35:48 ERROR framework.k8s.binding loop.go:65 add binding event handler failed (the server does not allow this method on the requested resource)
```

**Comment by arschles** [comment]
update as of 26a832a474c5180bf0d75bd2924580b8078b49ad: the watch loop can receive and decode the `Binding`, and the update function can now properly update the binding to `Pending`.

This is what the resulting binding TPR looks like:

``` console
ENG000656:binding aaronschlesinger$ k get binding.steward.deis.io s3 -o yaml
apiVersion: steward.deis.io/v1
kind: Binding
metadata:
  annotations:
    helm.sh/created: "1479412380"
  creationTimestamp: 2016-11-17T19:53:00Z
  labels:
    chart: claim-0.1.0
    component: wintering-drag-s3-uploader-binding
    release: wintering-drag
    type: broker
  name: s3
  namespace: default
  resourceVersion: "2093204"
  selfLink: /apis/steward.deis.io/v1/namespaces/default/bindings/s3
  uid: 71959610-acff-11e6-9b89-42010a800fc4
spec:
  id: 09e13f8c-8dee-480d-9e29-896ae12534fa
  instance_ref:
    kind: Instance
    name: s3
    namespace: default
  parameters: null
  secret_name: s3-demo-secret
status:
  state: Pending
```

The following changes need to be made:
- `Broker`'s watch and update functions need to use the dynamic client
- `ServiceClass`'s create function needs to use the dynamic client
- `Instance`'s watch and update functions need to use the dynamic client

**Comment by arschles** [comment]
Updated `./k8s/instance` to use the dynamic client as of cdae9f6b7b4ac144ba19a01322eb7eac4e136e4a

**Comment by arschles** [comment]
Current status as of 2901430: `Broker`s can be submitted, and `steward-cf` will make the `GET /v2/catalog` request on the backing CF broker API, translate the returned service catalog to `ServiceClass`es, and write them back to Kubernetes.

Here's the installation of the `Broker` (using the helm charts in https://github.com/deis/steward-demo-s3/pull/8):

``` console
ENG000656:broker aaronschlesinger$ helm install . --namespace=steward --set BrokerReleaseName=opinionated-ni
NAME: bailing-kudu
LAST DEPLOYED: Thu Nov 17 16:19:24 2016
NAMESPACE: steward
STATUS: DEPLOYED

RESOURCES:
==> extensions/v1beta1/ThirdPartyResourceData
NAME      LABELS                                                                                         DATA
s3        chart=claim-0.1.0,component=bailing-kudu-s3-uploader-broker,release=bailing-kudu,type=broker   {"Spec":{"password":"password","url":"http://opini...


ENG000656:broker aaronschlesinger$ ks get serviceclass
NAME              LABELS    DATA
s3-demo-service   <none>    {"bindable":true,"broker_name":"s3","broker_ref":{...
```

And here are the accompanying logs in `steward-cf`:

``` console
ENG000656:s3-service-provider aaronschlesinger$ ks logs -f opinionated-ni-steward-909912106-9epta
00:19:09 INFO   main.go:14 steward-cf version devel starting
00:19:09 INFO  framework.web.api router.go:23 starting API server on port 8080
00:19:24 DEBUG framework.k8s.broker loop.go:41 broker loop received event
00:19:24 DEBUG lib rest_client.go:72 CF client making GET request to http://username:password@opinionated-ni-broker.steward.svc.cluster.local:3000/v2/catalog
00:19:24 DEBUG framework.k8s.broker loop.go:41 broker loop received event
00:19:24 DEBUG framework.k8s.broker loop.go:41 broker loop received event
```

**Comment by arschles** [comment]
LGTM

**Comment by krancour** [comment]
Note that this PR features @arschles' and my own combined efforts. After much back and forth, we're mutually LGTM'ing one another's contributions to this PR.

**Pull request merged**
